services:
  beertracker:
    image: beertracker:latest
    environment:
      - DATABASE_URL=postgres://beertracker:nopass@database/beertracker
    ports:
      - 8000:8000

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=beertracker
      - POSTGRES_PASSWORD=nopass
      - POSTGRES_DB=beertracker
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
